-- MySQL Script generated by MySQL Workbench
-- Fri Mar 19 10:29:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Escuela_Danza_Proyecto_BD
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Escuela_Danza_Proyecto_BD` ;

-- -----------------------------------------------------
-- Schema Escuela_Danza_Proyecto_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escuela_Danza_Proyecto_BD` DEFAULT CHARACTER SET utf8 ;
USE `Escuela_Danza_Proyecto_BD` ;

-- -----------------------------------------------------
-- Table `Escuela_Danza_Proyecto_BD`.`ALUMNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela_Danza_Proyecto_BD`.`ALUMNO` (
  `id_alumno` INT NOT NULL,
  `Nombre` VARCHAR(70) NULL,
  `Apellido1` VARCHAR(70) NULL,
  `Apellido2` VARCHAR(70) NULL,
  `Telefono` INT NULL,
  `Email` VARCHAR(100) NULL,
  `fecha_nacimiento` DATE NULL,
  `fecha_matricula` DATE NULL,
  PRIMARY KEY (`id_alumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela_Danza_Proyecto_BD`.`FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela_Danza_Proyecto_BD`.`FACTURA` (
  `id_factura` INT NOT NULL,
  `fecha_factura` DATE NULL,
  `estado_factura` TINYINT NULL,
  `comentarios` VARCHAR(200) NULL,
  `total_factura` INT NULL,
  `ALUMNO_id_alumno` INT NOT NULL,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_FACTURA_ALUMNO_idx` (`ALUMNO_id_alumno` ASC) VISIBLE,
  CONSTRAINT `fk_FACTURA_ALUMNO`
    FOREIGN KEY (`ALUMNO_id_alumno`)
    REFERENCES `Escuela_Danza_Proyecto_BD`.`ALUMNO` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela_Danza_Proyecto_BD`.`MONITOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela_Danza_Proyecto_BD`.`MONITOR` (
  `id_monitor` INT NOT NULL,
  `Nombre` VARCHAR(70) NULL,
  `Apellido1` VARCHAR(95) NULL,
  `Apellido2` VARCHAR(96) NULL,
  `telefono` INT NULL,
  `dni` VARCHAR(45) NULL,
  PRIMARY KEY (`id_monitor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela_Danza_Proyecto_BD`.`MATERIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela_Danza_Proyecto_BD`.`MATERIA` (
  `id_materia` INT NOT NULL,
  `Nombre` VARCHAR(90) NULL,
  `dia/semana` VARCHAR(100) NULL,
  `hora` TIME NULL,
  `importe` INT NULL,
  `MONITOR_id_monitor` INT NOT NULL,
  PRIMARY KEY (`id_materia`),
  INDEX `fk_MATERIA_MONITOR1_idx` (`MONITOR_id_monitor` ASC) VISIBLE,
  CONSTRAINT `fk_MATERIA_MONITOR1`
    FOREIGN KEY (`MONITOR_id_monitor`)
    REFERENCES `Escuela_Danza_Proyecto_BD`.`MONITOR` (`id_monitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela_Danza_Proyecto_BD`.`FACTURA_has_MATERIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela_Danza_Proyecto_BD`.`FACTURA_has_MATERIA` (
  `FACTURA_id_factura` INT NOT NULL,
  `MATERIA_id_materia` INT NOT NULL,
  PRIMARY KEY (`FACTURA_id_factura`, `MATERIA_id_materia`),
  INDEX `fk_FACTURA_has_MATERIA_MATERIA1_idx` (`MATERIA_id_materia` ASC) VISIBLE,
  INDEX `fk_FACTURA_has_MATERIA_FACTURA1_idx` (`FACTURA_id_factura` ASC) VISIBLE,
  CONSTRAINT `fk_FACTURA_has_MATERIA_FACTURA1`
    FOREIGN KEY (`FACTURA_id_factura`)
    REFERENCES `Escuela_Danza_Proyecto_BD`.`FACTURA` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURA_has_MATERIA_MATERIA1`
    FOREIGN KEY (`MATERIA_id_materia`)
    REFERENCES `Escuela_Danza_Proyecto_BD`.`MATERIA` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela_Danza_Proyecto_BD`.`MATERIA_has_ALUMNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela_Danza_Proyecto_BD`.`MATERIA_has_ALUMNO` (
  `MATERIA_id_materia` INT NOT NULL,
  `ALUMNO_id_alumno` INT NOT NULL,
  `fecha_inicio_materia` DATE NULL,
  `fecha_final_materia` DATE NULL,
  PRIMARY KEY (`MATERIA_id_materia`, `ALUMNO_id_alumno`),
  INDEX `fk_MATERIA_has_ALUMNO_ALUMNO1_idx` (`ALUMNO_id_alumno` ASC) VISIBLE,
  INDEX `fk_MATERIA_has_ALUMNO_MATERIA1_idx` (`MATERIA_id_materia` ASC) VISIBLE,
  CONSTRAINT `fk_MATERIA_has_ALUMNO_MATERIA1`
    FOREIGN KEY (`MATERIA_id_materia`)
    REFERENCES `Escuela_Danza_Proyecto_BD`.`MATERIA` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATERIA_has_ALUMNO_ALUMNO1`
    FOREIGN KEY (`ALUMNO_id_alumno`)
    REFERENCES `Escuela_Danza_Proyecto_BD`.`ALUMNO` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
